### ISSUE TITLE
点击终止终端按钮，或者在终端执行 exit，浏览器控制台会报错

### ISSUE THREAD

**Issue by ysy8** [opensumi/ide-startup#123]
### 问题
点击`终止终端`按钮，或者在终端执行 `exit`，浏览器控制台会报错

### 版本
opensumi 依赖的模块包是 3.2.4

### 浏览器控制台错误
```
disposable.js:131 
TypeError: Cannot read properties of undefined (reading 'onRequestRedraw')
    at t.RenderService.setRenderer (xterm.js:1:107239)
    at Object.dispose (xterm-addon-webgl.js:1:93499)
    at a.dispose (xterm-addon-webgl.js:1:80532)
    at disposable.dispose (disposable.js:166:1)
    at t.AddonManager._wrappedAddonDispose (xterm.js:1:253216)
    at t.dispose (xterm.js:1:252929)
    at t.AddonManager.dispose (xterm.js:1:252822)
    at d.dispose (xterm.js:1:189863)
    at d.dispose (xterm.js:1:282229)
    at XTerm.dispose (xterm.js:150:1)
    at disposable.dispose (disposable.js:166:1)
    at TerminalClient.dispose (disposable.js:127:1)
    at TerminalClient.dispose (terminal.client.js:539:1)
    at TerminalController._disposeClient (terminal.controller.js:95:1)
    at terminal.controller.js:260:1
    at Emitter.fire (event.js:440:1)
    at TerminalGroupViewService.removeWidget (terminal.view.js:381:1)
    at Object.execute (terminal.command.js:76:1)
    at CommandRegistryImpl.executeCommand (command.js:87:1)
    at async index.js:128:1
```

**Comment by nxps** [comment]
core 最新版本会解决，关闭
