### ISSUE TITLE
yarn 命令运行错误

### ISSUE THREAD

**Issue by Yu-YuZhang** [opensumi/ide-startup#132]
Node Version:v18.17.0
Platform: Windows11
Compiler: (Windows) -->
error G:\HtmlCode\ide-startup\node_modules\node-pty: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: G:\HtmlCode\ide-startup\node_modules\node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.17.0 | win32 | x64
gyp info find Python using Python version 3.8.20 found at "G:\miniconda3\envs\py38env\python.exe"

gyp http GET https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v18.17.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.17.0/win-x64/node.lib
gyp info find VS using VS2017 (15.9.35324.217) found at:
gyp info find VS "G:\Microsoft Visual Studio\2017\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn G:\miniconda3\envs\py38env\python.exe
gyp info spawn args [
gyp info spawn args 'C:\Users\YuTong\AppData\Local\Yarn\Data\global\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'G:\HtmlCode\ide-startup\node_modules\node-pty\build\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\Users\YuTong\AppData\Local\Yarn\Data\global\node_modules\node-gyp\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\Users\YuTong\AppData\Local\node-gyp\Cache\18.17.0\include\node\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\Users\YuTong\AppData\Local\node-gyp\Cache\18.17.0',
gyp info spawn args '-Dnode_gyp_dir=C:\Users\YuTong\AppData\Local\Yarn\Data\global\node_modules\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\Users\\YuTong\\AppData\\Local\\node-gyp\\Cache\\18.17.0\\<(target_arch)\\node.lib',
gyp info spawn args '-Dmodule_root_dir=G:\HtmlCode\ide-startup\node_modules\node-pty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'G:\HtmlCode\ide-startup\node_modules\node-pty\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn G:\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
G:\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: ������ Spectre ���⣬���Ҳ��� Spectre ����⡣��֤ Visual Studio �������ɰ��� Spectre ����⡣�й���ϸ��Ϣ������� [https://aka.ms/Ofhn4c��](https://aka.ms/Ofhn4c%EF%BF%BD%EF%BF%BD) [G:\HtmlCode\ide-startup\node_modules\node-pty\build\conpty.vcxproj]
conpty.cc
path_util.cc
win_delay_load_hook.cc
LINK : fatal error LNK1181: �޷��������ļ���DelayImp.lib�� [G:\HtmlCode\ide-startup\node_modules\node-pty\build\conpty.vcxproj]
G:\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: ������ Spectre ���⣬���Ҳ��� Spectre ����⡣��֤ Visual Studio �������ɰ��� Spectre ����⡣�й���ϸ��Ϣ������� [https://aka.ms/Ofhn4c��](https://aka.ms/Ofhn4c%EF%BF%BD%EF%BF%BD) [G:\HtmlCode\ide-startup\node_modules\node-pty\build\conpty_console_list.vcxproj]
conpty_console_list.cc
win_delay_load_hook.cc
LINK : fatal error LNK1181: �޷��������ļ���DelayImp.lib�� [G:\HtmlCode\ide-startup\node_modules\node-pty\build\conpty_console_list.vcxproj]
Agent.cc
AgentCreateDesktop.cc
ConsoleFont.cc
ConsoleInput.cc
ConsoleInputReencoding.cc
ConsoleLine.cc
DebugShowInput.cc
DefaultInputMap.cc
EventLoop.cc
InputMap.cc
LargeConsoleRead.cc
NamedPipe.cc
Scraper.cc
Terminal.cc
Win32Console.cc
Win32ConsoleBuffer.cc
main.cc
BackgroundDesktop.cc
Buffer.cc
DebugClient.cc
GenRandom.cc
OwnedHandle.cc
StringUtil.cc
WindowsSecurity.cc
WindowsVersion.cc
WinptyAssert.cc
WinptyException.cc
WinptyVersion.cc
win_delay_load_hook.cc
�������ɴ���
g:\htmlcode\ide-startup\node_modules\node-pty\deps\winpty\src\agent\agent.cc(231): warning C4722: ��Agent::~Agent��: ����������Զ���᷵�أ����ܻᷢ���ڴ�й© [G:\HtmlCode\ide-startup\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
All 1982 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
����ɴ��������
winpty-agent.vcxproj -> G:\HtmlCode\ide-startup\node_modules\node-pty\build\Release\winpty-agent.exe
AgentLocation.cc
winpty.cc
BackgroundDesktop.cc
Buffer.cc
DebugClient.cc
GenRandom.cc
OwnedHandle.cc
StringUtil.cc
WindowsSecurity.cc
WindowsVersion.cc
WinptyAssert.cc
WinptyException.cc
WinptyVersion.cc
win_delay_load_hook.cc
���ڴ����� G:\HtmlCode\ide-startup\node_modules\node-pty\build\Release\winpty.lib �Ͷ��� G:\HtmlCode\ide-startup\node_modules\node-pty\build\Release\winpty.exp
�������ɴ���
All 1156 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
����ɴ��������
winpty.vcxproj -> G:\HtmlCode\ide-startup\node_modules\node-pty\build\Release\winpty.dll
gyp ERR! build error
gyp ERR! stack Error: G:\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess. (C:\Users\YuTong\AppData\Local\Yarn\Data\global\node_modules\node-gyp\lib\build.js:216:23)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "F:\nvm\nodejs\nodejs\node.exe" "C:\Users\YuTong\AppData\Local\Yarn\Data\global\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd G:\HtmlCode\ide-startup\node_modules\node-pty

**Comment by Yu-YuZhang** [comment]
[2024/11/14 02:29:07] [node:error] IPty#spawn native exception Error: Cannot find module '../build/Release/conpty.node'
Require stack:
- G:\HtmlCode\ide-startup\node_modules\node-pty\lib\windowsPtyAgent.js
- G:\HtmlCode\ide-startup\node_modules\node-pty\lib\windowsTerminal.js
- G:\HtmlCode\ide-startup\node_modules\node-pty\lib\index.js
- G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\lib\node\pty.proxy.js
- G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\lib\node\pty.manager.js
- G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\lib\node\pty.js
- G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\lib\node\index.js
- G:\HtmlCode\ide-startup\src\node\common-modules.ts
- G:\HtmlCode\ide-startup\src\node\index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename (G:\HtmlCode\ide-startup\node_modules\tsconfig-paths\src\register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new WindowsPtyAgent (G:\HtmlCode\ide-startup\node_modules\node-pty\src\windowsPtyAgent.ts:66:26)
    at new WindowsTerminal (G:\HtmlCode\ide-startup\node_modules\node-pty\src\windowsTerminal.ts:51:19)
    at Object.spawn (G:\HtmlCode\ide-startup\node_modules\node-pty\src\index.ts:30:10)
    at PtyServiceProxy.$spawn (G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\src\node\pty.proxy.ts:120:27)
    at PtyServiceManager.spawn (G:\HtmlCode\ide-startup\node_modules\@opensumi\ide-terminal-next\src\node\pty.manager.ts:98:56)
