### ISSUE TITLE
java项目,主方法运行报错

### ISSUE THREAD

**Issue by leafleo** [opensumi/ide-startup#133]
说明:   java项目run主方法, 报does not export sun.security.action to unnamed module, 在本地 vscode里面可以正常运行

环境: 
jdk: 17
nodejs: v18.19.0

启动配置:
<img width="611" alt="image" src="https://github.com/user-attachments/assets/a940f5c1-8382-4ac3-9fa2-3b48b5bd2b2f" />

安装的扩展: 
<img width="350" alt="image" src="https://github.com/user-attachments/assets/2906bbe5-311c-4442-999c-69971d09b69b" />

运行错误:
[Error - 4:35:00 PM] 2024年12月21日 下午4:35:00 [error response][launch]: class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x328bf1e1) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x328bf1e1
class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x328bf1e1) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x328bf1e1
java.lang.IllegalAccessError: class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x328bf1e1) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x328bf1e1
	at com.microsoft.java.debug.core.adapter.AdapterUtils.getTmpDir(AdapterUtils.java:356)
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createTempFile(AdapterUtils.java:375)
	at com.microsoft.java.debug.core.adapter.AdapterUtils.generateArgfile(AdapterUtils.java:345)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:131)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:80)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by life2015** [comment]
启动配置里面  vmArgs 两边加一下双引号

**Comment by leafleo** [comment]
启动配置里面 vmArgs 两边加一下双引号, 还是报错, 烦劳帮我再看看
![image](https://github.com/user-attachments/assets/5afed48c-dd28-4828-966f-82ee6c20d6c5)

错误信息:
[Error - 6:32:45 PM] 2024年12月23日 下午6:32:45 [error response][launch]: class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x48ff02e3) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x48ff02e3
class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x48ff02e3) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x48ff02e3
java.lang.IllegalAccessError: class com.microsoft.java.debug.core.adapter.AdapterUtils (in unnamed module @0x48ff02e3) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x48ff02e3
	at com.microsoft.java.debug.core.adapter.AdapterUtils.getTmpDir(AdapterUtils.java:356)
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createTempFile(AdapterUtils.java:375)
	at com.microsoft.java.debug.core.adapter.AdapterUtils.generateArgfile(AdapterUtils.java:345)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:131)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:80)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by life2015** [comment]
看起来是 Java Debug 插件可能是有些老旧了，试一下新版本的 Java Debug。我自己用的是 0.57.2024041008，可以找个高版本的试试

**Comment by leafleo** [comment]
我使用是最新的main 分支进行编译运行的,  烦劳提供下文档链接协助我修改的扩展市场源, 以便快速找到高版本并兼容的 java debug扩展
<img width="378" alt="image" src="https://github.com/user-attachments/assets/98c13632-3cf7-4295-b663-48840276ef76" />
