### ISSUE TITLE
cannot open menu

### ISSUE THREAD

**Issue by jacksontwu** [opensumi/ide-startup#4]
使用的最新版编译完成后，打开页面无法打开目录。
- platform: Alpine Linux 3.14
- [ide-startup](https://github.com/opensumi/ide-startup): latest

![截图](https://user-images.githubusercontent.com/59786894/156685337-653f8c99-e331-4bea-88f2-797f7f59118f.PNG)

**Comment by jacksontwu** [comment]
```bash
file-tree-model.service.js:323 Uncaught TypeError: Cannot read properties of undefined (reading 'root')
    at FileTreeModelService.handleItemClick (file-tree-model.service.js:323:1)
    at file-tree.js:214:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:389:1)
    at executeDispatchesInOrder (react-dom.development.js:411:1)
    at executeDispatchesAndRelease (react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287:1)
    at forEachAccumulated (react-dom.development.js:3259:1)
    at runEventsInBatch (react-dom.development.js:3304:1)
    at runExtractedPluginEventsInBatch (react-dom.development.js:3514:1)
    at handleTopLevel (react-dom.development.js:3558:1)
    at batchedEventUpdates$1 (react-dom.development.js:21871:1)
    at batchedEventUpdates (react-dom.development.js:795:1)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3568:1)
    at attemptToDispatchEvent (react-dom.development.js:4267:1)
    at dispatchEvent (react-dom.development.js:4189:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at discreteUpdates$1 (react-dom.development.js:21887:1)
    at discreteUpdates (react-dom.development.js:806:1)
    at dispatchDiscreteEvent (react-dom.development.js:4168:1)
FileTreeModelService.handleItemClick @ file-tree-model.service.js:323
(anonymous) @ file-tree.js:214
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:411
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
command.js:95 Uncaught (in promise) HANDLER_NOT_FOUND: The command 'filetree.open.folder' cannot be executed. There are no active handlers available for the command.
    at CommandRegistryImpl.executeCommand (http://localhost:8080/bundle.js:48634:21)
    at async CommandOpener.open (http://localhost:8080/bundle.js:39638:9)
    at async OpenerService.open (http://localhost:8080/bundle.js:39889:29)
```

**Comment by Aaaaash** [comment]
在项目根目录创建一个 workspace 文件夹，或者 URL query 加一个 `?workspaceDir=/path/to/dir`
